/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cantor_Interface;

import base_datos.Conector;
import cantor.Artista;
import cantor.Canario;
import cantor.Gallo;
import cantor.Instrumento;
import cantor.SerCantor;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author alejo
 */
public class Modificar extends javax.swing.JFrame {

    /**
     * Creates new form Modificar
     */
    Conector conn = new Conector();
    
    public Modificar() {
        
        initComponents();
        setLocationRelativeTo(null);
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_modificacion = new javax.swing.JButton();
        _LISTA_DE_ARTISTAS = new javax.swing.JComboBox<>();
        _ELIMINAR_ = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        _salida_nacimiento = new javax.swing.JTextField();
        _salida_edad = new javax.swing.JTextField();
        _salida_instrumento = new javax.swing.JTextField();
        _salida_canto = new javax.swing.JTextField();

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Instrumento que toca");

        jLabel1.setText("MODIFICAR/ELIMINAR ARTISTA");

        btn_modificacion.setText("Modificar");
        btn_modificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificacionActionPerformed(evt);
            }
        });

        _LISTA_DE_ARTISTAS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        _LISTA_DE_ARTISTAS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                _LISTA_DE_ARTISTASItemStateChanged(evt);
            }
        });
        _LISTA_DE_ARTISTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _LISTA_DE_ARTISTASActionPerformed(evt);
            }
        });

        _ELIMINAR_.setText("Eliminarlo");
        _ELIMINAR_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _ELIMINAR_ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Tipo", "ARTISTA", "GALLO", "CANARIO" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Momento");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Edad");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Fecha de Nacimiento");

        _salida_nacimiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        _salida_edad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        _salida_instrumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        _salida_instrumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _salida_instrumentoActionPerformed(evt);
            }
        });

        _salida_canto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_LISTA_DE_ARTISTAS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, 307, Short.MAX_VALUE)
                            .addComponent(_salida_instrumento))
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_modificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_ELIMINAR_, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(172, 172, 172))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(_salida_canto)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(_salida_nacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(_salida_edad, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_LISTA_DE_ARTISTAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_salida_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(_salida_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_salida_instrumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(_salida_canto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificacion)
                    .addComponent(_ELIMINAR_))
                .addGap(20, 20, 20))
        );

        jComboBox1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _LISTA_DE_ARTISTASItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event__LISTA_DE_ARTISTASItemStateChanged
        // TODO add your handling code here:
        try {
            if (evt.getStateChange() == ItemEvent.SELECTED) {
                if (jComboBox1.getSelectedIndex() > 0) {
                    if (jComboBox1.getSelectedIndex() == 1) {
                        ArrayList<Artista> art = conn.getGestorArtista().getDatos();
                        for (Artista artista : art) {
                            if (_LISTA_DE_ARTISTAS.getSelectedItem().equals(artista.nombre)) {
                                _salida_nacimiento.setText(String.valueOf(artista.fechaNacimiento));
                                _salida_edad.setText(String.valueOf(artista.calcularEdad()));
                                _salida_instrumento.setText(artista.usa.nombre);
                                _salida_canto.setText(artista.cuando.tipo);
                            }
                        }
                    }
                    if (jComboBox1.getSelectedIndex() == 2) {
                        ArrayList<Gallo> gallos = conn.getGestorGallo().getDatos();
                        for (Gallo gallo : gallos) {
                            if (_LISTA_DE_ARTISTAS.getSelectedItem().equals(gallo.nombre)) {
                                _salida_nacimiento.setText(String.valueOf(gallo.fechaNacimiento));
                                _salida_edad.setText(String.valueOf(gallo.calcularEdad()));
                                _salida_canto.setText(gallo.cuando.tipo);
                                _salida_instrumento.setText("No aplica");
                            }
                        }
                    }
                    if (jComboBox1.getSelectedIndex() == 3) {
                        ArrayList<Canario> canarios = conn.getGestorCanario().getDatos();
                        for (Canario canario : canarios) {
                            if (_LISTA_DE_ARTISTAS.getSelectedItem().equals(canario.nombre)) {
                                _salida_nacimiento.setText(String.valueOf(canario.fechaNacimiento));
                                _salida_edad.setText(String.valueOf(canario.calcularEdad()));
                                _salida_canto.setText(canario.cuando.tipo);
                                _salida_instrumento.setText("No aplica");
                            }
                        }
                    }
                } else {
                    String[] arreglo = {""};
                    this._LISTA_DE_ARTISTAS.setModel(new DefaultComboBoxModel(arreglo));
                }
            }
        } catch (Exception ex) {
            System.out.println("Error" + ex.getMessage());
        }
    }//GEN-LAST:event__LISTA_DE_ARTISTASItemStateChanged

    private void _LISTA_DE_ARTISTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__LISTA_DE_ARTISTASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__LISTA_DE_ARTISTASActionPerformed

    private void btn_modificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificacionActionPerformed
        // TODO add your handling code here:
        String item = String.valueOf(_LISTA_DE_ARTISTAS.getSelectedItem());

//        View host = new View();
//        SerCantor.artistas.get(host.POSICION_LISTA(item)).tipo = modificacion_TIPO.getText();
//        SerCantor.artistas.get(host.POSICION_LISTA(item)).usa[0].nombre = modificacion_NOMBRE_INSTRUMENTO.getText();
//        SerCantor.artistas.get(host.POSICION_LISTA(item)).usa[0].tipo = modificacion_TIPO_INSTRUMENTO.getText();
//        SerCantor.artistas.get(host.POSICION_LISTA(item)).canto = modificacion_CANTAR.getText();
    }//GEN-LAST:event_btn_modificacionActionPerformed

    private void _ELIMINAR_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__ELIMINAR_ActionPerformed
//        String seleccion = String.valueOf(jComboBox1.getSelectedItem());
//        System.out.println(seleccion);
//        int n = JOptionPane.showConfirmDialog(null, "Seguro que quieres borrar el artista", "", JOptionPane.YES_NO_OPTION);
//        try{
//            if (n == JOptionPane.YES_OPTION) {
//                String value = (String) _LISTA_DE_ARTISTAS.getSelectedItem();
//                
//                if (seleccion.equals("ARTISTA")) {
//                    conn.getGestorArtista().borrarDato(elemento);
//                } else {
//                    if (seleccion.equals("GALLO")) {
//                        conn.deleteGallo(value);
//                    } else {
//                        conn.deleteCanario(value);
//                    }
//                }
//                JOptionPane.showMessageDialog(null, "Artista borrado");
//            } else {
//                JOptionPane.showMessageDialog(null, "El Artista no fue borrado");
//            }
//        }catch(Exception ex){
//            System.out.println("Error");
//        }
    }//GEN-LAST:event__ELIMINAR_ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        try{
            if(evt.getStateChange() == ItemEvent.SELECTED){
                if (jComboBox1.getSelectedIndex() >0) {
                    if (jComboBox1.getSelectedIndex()==1) {
                        ArrayList<Artista> art = conn.getGestorArtista().getDatos();
                        String[] arreglo1 = convertirArrayArregloArtista(art);
                        this._LISTA_DE_ARTISTAS.setModel(new DefaultComboBoxModel(arreglo1));
                        
                    }
                    if (jComboBox1.getSelectedIndex()==2) {
                        ArrayList<Gallo> gallos = conn.getGestorGallo().getDatos();
                        String[] arreglo2 = convertirArrayArregloGallo(gallos);
                        this._LISTA_DE_ARTISTAS.setModel(new DefaultComboBoxModel(arreglo2));
                    }
                    if (jComboBox1.getSelectedIndex()==3) {
                        ArrayList<Canario> canarios = conn.getGestorCanario().getDatos();
                        String[] arreglo3 = convertirArrayArregloCanario(canarios);
                        this._LISTA_DE_ARTISTAS.setModel(new DefaultComboBoxModel(arreglo3));
                    }
                }
            }
        }catch(Exception ex){
            System.out.println("Error"+ ex.getMessage());
        }
        
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void _salida_instrumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__salida_instrumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__salida_instrumentoActionPerformed
    
    public String[] convertirArrayArregloArtista(ArrayList<Artista> array){
        String[] arreglo = new String[array.size()];
        for (int i = 0; i < array.size(); i++) {
            arreglo[i]= array.get(i).nombre;
        }
        return arreglo;
    }
    public String[] convertirArrayArregloGallo(ArrayList<Gallo> array){
        String[] arreglo = new String[array.size()];
        for (int i = 0; i < array.size(); i++) {
            arreglo[i]= array.get(i).nombre;
        }
        return arreglo;
    }
    public String[] convertirArrayArregloCanario(ArrayList<Canario> array){
        String[] arreglo = new String[array.size()];
        for (int i = 0; i < array.size(); i++) {
            arreglo[i]= array.get(i).nombre;
        }
        return arreglo;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _ELIMINAR_;
    private javax.swing.JComboBox<String> _LISTA_DE_ARTISTAS;
    private javax.swing.JTextField _salida_canto;
    private javax.swing.JTextField _salida_edad;
    private javax.swing.JTextField _salida_instrumento;
    private javax.swing.JTextField _salida_nacimiento;
    private javax.swing.JButton btn_modificacion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
